version: '3.8'

services:
  mdbook:
    build:
      context: .
      dockerfile: mdbook.dockerfile
    volumes:
      - ./src:/app/src:ro
      - ./book.toml:/app/book.toml:ro
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "mdbook serve -n 0.0.0.0"
