version: '3.8'

services:
  mdbook:
    build:
      context: .
      dockerfile: mdbook.dockerfile
    volumes:
      - .:/book
    working_dir: /book
    ports:
      - "3000:3000"
    command: sh -c "mdbook serve -n 0.0.0.0"
